services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-php
    container_name: php_container
    volumes:
      - ./:/var/www/html
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "${WEB_HOST_PORT}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_network

  db:
    image: postgres:latest
    container_name: db_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data: